"""Durable regression check for the single-use launch token (defect d10).

Run with: `python3 tests/fixtures/review/token_single_use_check.py` (exit 0 =
pass). It stubs the core `grogu_review` module (a separate workstream) so it can
import `grogu_review_server` and exercise the real token logic without a browser:

  * `_Context.consume_token` accepts a correct token exactly once, then fails
    closed for every replay, and refuses an empty or wrong token without
    spending the real one;
  * under concurrent replay, exactly one caller wins (race-safe);
  * end to end, a second `GET /?t=<token>` returns 403, not another 303 + cookie.

The tester owns tests/test_*.py; this lives in the fixtures the surface
workstream owns.
"""

import http.client
import os
import subprocess
import sys
import tempfile
import threading
import types
from pathlib import Path

REPO_SRC = Path(__file__).resolve().parents[3] / "src"
sys.path.insert(0, str(REPO_SRC))

# Minimal stand-in for the core module so grogu_review_server imports; the token
# exchange never touches the review store, so a no-op ReviewStore is enough.
_stub = types.ModuleType("grogu_review")


class _ReviewError(Exception):
    ...


class _ReviewStore:
    def __init__(self, plans):
        self.plans = plans


_stub.ReviewError = _ReviewError
_stub.ReviewStore = _ReviewStore
sys.modules.setdefault("grogu_review", _stub)

import grogu_review_server as srv  # noqa: E402

failures = 0


def check(name, cond):
    global failures
    if cond:
        print("PASS", name)
    else:
        failures += 1
        print("FAIL", name)


def make_context():
    return srv._Context(
        plan_id="p-test",
        role="reviewer",
        store=object(),
        review=object(),
        stage="",
        timeout=3600,
    )


# -- unit: consume_token is single-use and fails closed ----------------------

ctx = make_context()
token = ctx.token  # grogu-allow-secret: a per-run token generated by the server under test
check("wrong token is refused and does not spend the real one", ctx.consume_token("nope") is False)
check("empty token is refused", ctx.consume_token("") is False)
check("correct token is accepted once", ctx.consume_token(token) is True)
check("replay of a spent token fails closed", ctx.consume_token(token) is False)
check("empty token after spend still fails closed", ctx.consume_token("") is False)

# -- unit: concurrent replay -> exactly one winner ---------------------------

ctx2 = make_context()
token2 = ctx2.token  # grogu-allow-secret: a per-run token generated by the server under test
results = []
barrier = threading.Barrier(16)


def race():
    barrier.wait()
    results.append(ctx2.consume_token(token2))


threads = [threading.Thread(target=race) for _ in range(16)]
for t in threads:
    t.start()
for t in threads:
    t.join()
check("concurrent replay yields exactly one winner", results.count(True) == 1)

# -- end to end: the HTTP route returns 403 on replay ------------------------


def http_route_check():
    global failures
    home = tempfile.mkdtemp()
    os.environ["GROGU_HOME"] = home
    os.environ["HOME"] = home
    Path(home, "gc").write_text("[init]\n\tdefaultBranch = main\n", encoding="utf8")
    os.environ["GIT_CONFIG_GLOBAL"] = str(Path(home, "gc"))
    for leaked in ("GROGU_ROLE", "GROGU_PLAN", "GROGU_AGENT"):
        os.environ.pop(leaked, None)
    repo = Path(tempfile.mkdtemp())
    env = {
        **os.environ,
        "GIT_AUTHOR_NAME": "t",
        "GIT_AUTHOR_EMAIL": "t@t",
        "GIT_COMMITTER_NAME": "t",
        "GIT_COMMITTER_EMAIL": "t@t",
    }
    subprocess.run(["git", "init", "-q", str(repo)], check=True)
    subprocess.run(["git", "commit", "--allow-empty", "-qm", "i"], cwd=repo, check=True, env=env)

    import grogu_plans

    store = grogu_plans.PlanStore(repo)
    plan = store.create("Token test")
    pid = plan["id"]
    store.write_stage(pid, "implementation", "a body", role="architect")

    info = {}
    srv.serve(pid, store=store, port=0, timeout=3600, on_ready=info.update, block=False)
    port = info["port"]
    token = info["token"]

    def raw(path, headers):
        conn = http.client.HTTPConnection("127.0.0.1", port, timeout=5)
        conn.request("GET", path, headers=headers)
        resp = conn.getresponse()
        resp.read()
        conn.close()
        return resp.status

    host = {"Host": f"127.0.0.1:{port}"}
    first = raw(f"/?t={token}", host)
    second = raw(f"/?t={token}", host)
    check("first exchange returns 303", first == 303)
    check("replayed exchange returns 403 (single-use)", second == 403)

    # A cross-origin/host replay is still refused before the token is even read.
    bad_host = raw(f"/?t={token}", {"Host": "evil.example.com"})
    check("replay with a bad Host is refused", bad_host == 403)


http_route_check()

if failures:
    print(f"\n{failures} FAILED")
    sys.exit(1)
print("\nALL PASS")
